//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.RefServicio1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefServicio1.ServicioCV1Soap")]
    public interface ServicioCV1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaExiste", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaExiste(string Usuario_o_Correo, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaExiste", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaExisteAsync(string Usuario_o_Correo, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaInformacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CuentaInformacion(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaInformacion", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CuentaInformacionAsync(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaAgregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaAgregar(string CorreoSeguro, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaAgregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaAgregarAsync(string CorreoSeguro, string Usuario, string Contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaDesactivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaDesactivar(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaDesactivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaDesactivarAsync(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaReactivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaReactivar(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaReactivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaReactivarAsync(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaActualizarContrasena", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaActualizarContrasena(int CodCuenta, string Contrasena, string ContrasenaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaActualizarContrasena", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaActualizarContrasenaAsync(int CodCuenta, string Contrasena, string ContrasenaNueva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaActualizarSeudonimo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaActualizarSeudonimo(int CodCuenta, string Seudonimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaActualizarSeudonimo", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaActualizarSeudonimoAsync(int CodCuenta, string Seudonimo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaActualizarLlave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] CuentaActualizarLlave(int CodCuenta, string Llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CuentaActualizarLlave", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> CuentaActualizarLlaveAsync(int CodCuenta, string Llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoListar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet InfoListar(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoListar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> InfoListarAsync(int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] InfoActualizar(string Apellidos, string Nombres, string Nacimiento, string Sexo, string EstadoCivil, string DNI, string Direccion, string Informacion, int CodCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> InfoActualizarAsync(string Apellidos, string Nombres, string Nacimiento, string Sexo, string EstadoCivil, string DNI, string Direccion, string Informacion, int CodCuenta);
        
        // CODEGEN: El parámetro 'Foto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoActualizarImagen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClienteWeb.RefServicio1.InfoActualizarImagenResponse InfoActualizarImagen(ClienteWeb.RefServicio1.InfoActualizarImagenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoActualizarImagen", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteWeb.RefServicio1.InfoActualizarImagenResponse> InfoActualizarImagenAsync(ClienteWeb.RefServicio1.InfoActualizarImagenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoDepartamentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UbigeoDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoDepartamentos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UbigeoDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoProvincias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UbigeoProvincias(string CodDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoProvincias", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UbigeoProvinciasAsync(string CodDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoDistritos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UbigeoDistritos(string CodDepartamento, string CodProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoDistritos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UbigeoDistritosAsync(string CodDepartamento, string CodProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoLugar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UbigeoLugar(string CodUbigeo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UbigeoLugar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UbigeoLugarAsync(string CodUbigeo);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InfoActualizarImagen", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InfoActualizarImagenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Foto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int CodCuenta;
        
        public InfoActualizarImagenRequest() {
        }
        
        public InfoActualizarImagenRequest(byte[] Foto, int CodCuenta) {
            this.Foto = Foto;
            this.CodCuenta = CodCuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InfoActualizarImagenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InfoActualizarImagenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] InfoActualizarImagenResult;
        
        public InfoActualizarImagenResponse() {
        }
        
        public InfoActualizarImagenResponse(string[] InfoActualizarImagenResult) {
            this.InfoActualizarImagenResult = InfoActualizarImagenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCV1SoapChannel : ClienteWeb.RefServicio1.ServicioCV1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCV1SoapClient : System.ServiceModel.ClientBase<ClienteWeb.RefServicio1.ServicioCV1Soap>, ClienteWeb.RefServicio1.ServicioCV1Soap {
        
        public ServicioCV1SoapClient() {
        }
        
        public ServicioCV1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCV1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCV1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCV1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] CuentaExiste(string Usuario_o_Correo, string Contrasena) {
            return base.Channel.CuentaExiste(Usuario_o_Correo, Contrasena);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaExisteAsync(string Usuario_o_Correo, string Contrasena) {
            return base.Channel.CuentaExisteAsync(Usuario_o_Correo, Contrasena);
        }
        
        public System.Data.DataSet CuentaInformacion(int CodCuenta) {
            return base.Channel.CuentaInformacion(CodCuenta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CuentaInformacionAsync(int CodCuenta) {
            return base.Channel.CuentaInformacionAsync(CodCuenta);
        }
        
        public string[] CuentaAgregar(string CorreoSeguro, string Usuario, string Contrasena) {
            return base.Channel.CuentaAgregar(CorreoSeguro, Usuario, Contrasena);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaAgregarAsync(string CorreoSeguro, string Usuario, string Contrasena) {
            return base.Channel.CuentaAgregarAsync(CorreoSeguro, Usuario, Contrasena);
        }
        
        public string[] CuentaDesactivar(int CodCuenta) {
            return base.Channel.CuentaDesactivar(CodCuenta);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaDesactivarAsync(int CodCuenta) {
            return base.Channel.CuentaDesactivarAsync(CodCuenta);
        }
        
        public string[] CuentaReactivar(int CodCuenta) {
            return base.Channel.CuentaReactivar(CodCuenta);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaReactivarAsync(int CodCuenta) {
            return base.Channel.CuentaReactivarAsync(CodCuenta);
        }
        
        public string[] CuentaActualizarContrasena(int CodCuenta, string Contrasena, string ContrasenaNueva) {
            return base.Channel.CuentaActualizarContrasena(CodCuenta, Contrasena, ContrasenaNueva);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaActualizarContrasenaAsync(int CodCuenta, string Contrasena, string ContrasenaNueva) {
            return base.Channel.CuentaActualizarContrasenaAsync(CodCuenta, Contrasena, ContrasenaNueva);
        }
        
        public string[] CuentaActualizarSeudonimo(int CodCuenta, string Seudonimo) {
            return base.Channel.CuentaActualizarSeudonimo(CodCuenta, Seudonimo);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaActualizarSeudonimoAsync(int CodCuenta, string Seudonimo) {
            return base.Channel.CuentaActualizarSeudonimoAsync(CodCuenta, Seudonimo);
        }
        
        public string[] CuentaActualizarLlave(int CodCuenta, string Llave) {
            return base.Channel.CuentaActualizarLlave(CodCuenta, Llave);
        }
        
        public System.Threading.Tasks.Task<string[]> CuentaActualizarLlaveAsync(int CodCuenta, string Llave) {
            return base.Channel.CuentaActualizarLlaveAsync(CodCuenta, Llave);
        }
        
        public System.Data.DataSet InfoListar(int CodCuenta) {
            return base.Channel.InfoListar(CodCuenta);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InfoListarAsync(int CodCuenta) {
            return base.Channel.InfoListarAsync(CodCuenta);
        }
        
        public string[] InfoActualizar(string Apellidos, string Nombres, string Nacimiento, string Sexo, string EstadoCivil, string DNI, string Direccion, string Informacion, int CodCuenta) {
            return base.Channel.InfoActualizar(Apellidos, Nombres, Nacimiento, Sexo, EstadoCivil, DNI, Direccion, Informacion, CodCuenta);
        }
        
        public System.Threading.Tasks.Task<string[]> InfoActualizarAsync(string Apellidos, string Nombres, string Nacimiento, string Sexo, string EstadoCivil, string DNI, string Direccion, string Informacion, int CodCuenta) {
            return base.Channel.InfoActualizarAsync(Apellidos, Nombres, Nacimiento, Sexo, EstadoCivil, DNI, Direccion, Informacion, CodCuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteWeb.RefServicio1.InfoActualizarImagenResponse ClienteWeb.RefServicio1.ServicioCV1Soap.InfoActualizarImagen(ClienteWeb.RefServicio1.InfoActualizarImagenRequest request) {
            return base.Channel.InfoActualizarImagen(request);
        }
        
        public string[] InfoActualizarImagen(byte[] Foto, int CodCuenta) {
            ClienteWeb.RefServicio1.InfoActualizarImagenRequest inValue = new ClienteWeb.RefServicio1.InfoActualizarImagenRequest();
            inValue.Foto = Foto;
            inValue.CodCuenta = CodCuenta;
            ClienteWeb.RefServicio1.InfoActualizarImagenResponse retVal = ((ClienteWeb.RefServicio1.ServicioCV1Soap)(this)).InfoActualizarImagen(inValue);
            return retVal.InfoActualizarImagenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteWeb.RefServicio1.InfoActualizarImagenResponse> ClienteWeb.RefServicio1.ServicioCV1Soap.InfoActualizarImagenAsync(ClienteWeb.RefServicio1.InfoActualizarImagenRequest request) {
            return base.Channel.InfoActualizarImagenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteWeb.RefServicio1.InfoActualizarImagenResponse> InfoActualizarImagenAsync(byte[] Foto, int CodCuenta) {
            ClienteWeb.RefServicio1.InfoActualizarImagenRequest inValue = new ClienteWeb.RefServicio1.InfoActualizarImagenRequest();
            inValue.Foto = Foto;
            inValue.CodCuenta = CodCuenta;
            return ((ClienteWeb.RefServicio1.ServicioCV1Soap)(this)).InfoActualizarImagenAsync(inValue);
        }
        
        public System.Data.DataSet UbigeoDepartamentos() {
            return base.Channel.UbigeoDepartamentos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UbigeoDepartamentosAsync() {
            return base.Channel.UbigeoDepartamentosAsync();
        }
        
        public System.Data.DataSet UbigeoProvincias(string CodDepartamento) {
            return base.Channel.UbigeoProvincias(CodDepartamento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UbigeoProvinciasAsync(string CodDepartamento) {
            return base.Channel.UbigeoProvinciasAsync(CodDepartamento);
        }
        
        public System.Data.DataSet UbigeoDistritos(string CodDepartamento, string CodProvincia) {
            return base.Channel.UbigeoDistritos(CodDepartamento, CodProvincia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UbigeoDistritosAsync(string CodDepartamento, string CodProvincia) {
            return base.Channel.UbigeoDistritosAsync(CodDepartamento, CodProvincia);
        }
        
        public System.Data.DataSet UbigeoLugar(string CodUbigeo) {
            return base.Channel.UbigeoLugar(CodUbigeo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UbigeoLugarAsync(string CodUbigeo) {
            return base.Channel.UbigeoLugarAsync(CodUbigeo);
        }
    }
}
